version: '3'

services:
  database:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: mysql/mysql-server:5.7.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"

  php:
    build: .
    container_name: php
    volumes:
      - ./:/var/www/html
    ports:
      - "8008:8008"
